language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t nishant28062022/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nishant28062022/react-test npm test

after_success:
  - docker build -t nishant28062022/multi-client ./client
  - docker build -t nishant28062022/multi-nginx ./nginx
  - docker build -t nishant28062022/multi-server ./server
  - docker build -t nishant28062022/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nishant28062022/multi-client
  - docker push nishant28062022/multi-nginx
  - docker push nishant28062022/multi-server
  - docker push nishant28062022/multi-worker
